### PR TITLE
Changed box layout to fit double relay board

### PR DESCRIPTION
**Pull request by phckopper**
* Widened PCB support to allow fitting the larger board (#2)
* Widened the box itself to ease wiring
* Moved Skadis mounting holes to bottom part (#5)

Change-type: major
Signed-off-by: Pedro Henrique Kopper <pedro.kopper@balena.io>

### CODE REVIEW

**Comment by phckopper** [comment]
Converted to draft as the design wasn't validated by printing yet.

**Comment by rcooke-warwick** [comment]
konstantinos also suggested we move the screws to the bottom instead of the top, for safety purposes

**Comment by phckopper** [comment]
Also changed the position of the C13/C14 connectors in order to make room for the wires

**Comment by phckopper** [comment]
@balena-ci I self-certify!

**Review by ghost — APPROVED** [review]

**Pull request merged**
